spring.cloud.stream:
  function.definition: supplier;consumer;
  bindings:
    consumer-in-0:
      destination: "sensor"
  solace.bindings.consumer-in-0.consumer:
    queueAdditionalSubscriptions: "sensor/>"
solace:
  java:
    host: tcp://mrrwtxvklyzl3.messaging.solace.cloud:55555
    msgVpn: msgvpn-rwtxvklyzk9
    clientUsername: solace-cloud-client
    clientPassword: 2bv9lctv5kl5k73dgn5o9al8s7
    connectRetries: -1
    reconnectRetries: -1
logging.level:
  root: info
  com.solace: info
  com.solacesystems.jcsmp: info
  org.springframework: info
  org.springframework.cloud: info
  org.springframework.integration: info

server.port: 8080
management.endpoints.web.exposure.include: "*"

