spring:
  cloud:
    stream:
      bindings:
        tempBindingInput:
          destination: TEMPS.Q
          group: SINK
          binder: local_solace
        tempBindingOutput:
          destination: sensor/temperature/fahrenheit
          binder: local_solace
        sensorReadingSupplier-out-0:
          destination: sensor/temperature/fahrenheit
          binder: local_solace
      binders:
        local_solace:
          type: solace
          environment:
            solace:
              java:
                host: tcp://mrrwtxvklyzl3.messaging.solace.cloud:55555
                msgVpn: msgvpn-rwtxvklyzk9
                clientUsername: solace-cloud-client
                clientPassword: 2bv9lctv5kl5k73dgn5o9al8s7
                connectRetries: -1
                reconnectRetries: -1
      solace:
        bindings:
          tempBindingInput:
            consumer:
              queueAdditionalSubscriptions: sensor/temperature/>
logging:
  level:
    root: INFO
    com.solace: INFO
    com.solacesystems.jcsmp: INFO
    org.springframework: INFO
    org.springframework.cloud: INFO
server:
  port: 8095
management:
  endpoints:
    web:
      exposure:
        include: "*"
